### ISSUE TITLE
GroupDM with no recipients other than the current user will not be displayed

### ISSUE THREAD

**Issue by sewnie** [diamondburned/ningen#5]
https://github.com/diamondburned/ningen/blob/92cbc1390b2a94e85e82d97e97edb7be72d127de/ningen.go#L473-L481

In the code snippet above, there is a check for if there are no recipients in a private channel. The problem with this is that in `DMRecipients`, the logged in user will not be in it, hence if there is a GroupDM with no recipients but the current user, the channel does not appear.

This bug occurs on gtkcord4 and i cannot see my personal GroupDM.

A workaround to this would be to simply remove the check, as such a channel is *impossible*. Or to check the channel's author and compare it to the logged in user's ID to see if it is a Self GroupDM.

**Comment by diamondburned** [comment]
I think if this is a valid use case, then I'm fine with dropping the check entirely.

**Comment by sewnie** [comment]
It seems that in the commit message of fe1b78f47f97f999a301549d17dcbd782f368aba, 'Ignore broken group DMs' it implies there are GroupDMs that are broken and have *no* recipients, but in this case the recipients is the user.

Is there a case where the GroupDMs are completely empty, with no recipients at all?

**Comment by diamondburned** [comment]
I'm not entirely sure myself. This must've caused some issue in the UI, but it might also just be a very minor issue. I think it's safe to revert this commit and see how that goes.

**Comment by sewnie** [comment]
This https://github.com/diamondburned/ningen/blob/92cbc1390b2a94e85e82d97e97edb7be72d127de/ningen.go#L236-L240

*might* be affiliated, but in my own testing the groupDM appears as normal during the ReadyEvent and `state.PrivateChannels`

**Comment by sewnie** [comment]
Sorry, but just another question: When `PrivateChannels` are sorted they are sorted by the last sent message, but i have a DM where there is no messages at all and it gets sorted at the top, ~~why is that?~~ it seems that the last message id is 0, when it should be at the bottom but it is not. on gtkcord4 the behavior is similar but the DM is at the bottom rather than at the top.

Is there a solution to this?

**Comment by diamondburned** [comment]
Probably just by adding an edge case in the sorting function.

The sort function acts like an `a < b` comparison, where `a` is put before `b` if `a < b`. Here, since channels with the latest messages are put on top, the comparison goes like `a.last_message > b.last_message` (invert order, so largest first, and compare based on the `last_message` field).

If `a` has a special condition that should put it on top, then it should return true. If `b` has a special condition that should put it on top, then it should return false.
